// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: measures.proto

package ch.heigvd.iict.dma.labo1.protobuf;

public final class MeasuresOuterClass {
  private MeasuresOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MeasureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ch.heigvd.iict.dma.labo1.protobuf.Measure)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>.ch.heigvd.iict.dma.labo1.protobuf.Measure.Status status = 2;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.ch.heigvd.iict.dma.labo1.protobuf.Measure.Status status = 2;</code>
     * @return The status.
     */
    ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Status getStatus();

    /**
     * <code>.ch.heigvd.iict.dma.labo1.protobuf.Measure.Type type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.ch.heigvd.iict.dma.labo1.protobuf.Measure.Type type = 3;</code>
     * @return The type.
     */
    ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Type getType();

    /**
     * <code>double value = 4;</code>
     * @return The value.
     */
    double getValue();

    /**
     * <code>.google.protobuf.Timestamp date = 5;</code>
     * @return Whether the date field is set.
     */
    boolean hasDate();
    /**
     * <code>.google.protobuf.Timestamp date = 5;</code>
     * @return The date.
     */
    com.google.protobuf.Timestamp getDate();
    /**
     * <code>.google.protobuf.Timestamp date = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getDateOrBuilder();
  }
  /**
   * Protobuf type {@code ch.heigvd.iict.dma.labo1.protobuf.Measure}
   */
  public static final class Measure extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ch.heigvd.iict.dma.labo1.protobuf.Measure)
      MeasureOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Measure.newBuilder() to construct.
    private Measure(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Measure() {
      status_ = 0;
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Measure();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.internal_static_ch_heigvd_iict_dma_labo1_protobuf_Measure_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.internal_static_ch_heigvd_iict_dma_labo1_protobuf_Measure_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.class, ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Builder.class);
    }

    /**
     * Protobuf enum {@code ch.heigvd.iict.dma.labo1.protobuf.Measure.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NEW = 0;</code>
       */
      NEW(0),
      /**
       * <code>OK = 1;</code>
       */
      OK(1),
      /**
       * <code>ERROR = 2;</code>
       */
      ERROR(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NEW = 0;</code>
       */
      public static final int NEW_VALUE = 0;
      /**
       * <code>OK = 1;</code>
       */
      public static final int OK_VALUE = 1;
      /**
       * <code>ERROR = 2;</code>
       */
      public static final int ERROR_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Status forNumber(int value) {
        switch (value) {
          case 0: return NEW;
          case 1: return OK;
          case 2: return ERROR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ch.heigvd.iict.dma.labo1.protobuf.Measure.Status)
    }

    /**
     * Protobuf enum {@code ch.heigvd.iict.dma.labo1.protobuf.Measure.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TEMPERATURE = 0;</code>
       */
      TEMPERATURE(0),
      /**
       * <code>PRECIPITATION = 1;</code>
       */
      PRECIPITATION(1),
      /**
       * <code>HUMIDITY = 2;</code>
       */
      HUMIDITY(2),
      /**
       * <code>PRESSURE = 3;</code>
       */
      PRESSURE(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>TEMPERATURE = 0;</code>
       */
      public static final int TEMPERATURE_VALUE = 0;
      /**
       * <code>PRECIPITATION = 1;</code>
       */
      public static final int PRECIPITATION_VALUE = 1;
      /**
       * <code>HUMIDITY = 2;</code>
       */
      public static final int HUMIDITY_VALUE = 2;
      /**
       * <code>PRESSURE = 3;</code>
       */
      public static final int PRESSURE_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Type forNumber(int value) {
        switch (value) {
          case 0: return TEMPERATURE;
          case 1: return PRECIPITATION;
          case 2: return HUMIDITY;
          case 3: return PRESSURE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.getDescriptor().getEnumTypes().get(1);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ch.heigvd.iict.dma.labo1.protobuf.Measure.Type)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_ = 0;
    /**
     * <code>.ch.heigvd.iict.dma.labo1.protobuf.Measure.Status status = 2;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.ch.heigvd.iict.dma.labo1.protobuf.Measure.Status status = 2;</code>
     * @return The status.
     */
    @java.lang.Override public ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Status getStatus() {
      ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Status result = ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Status.forNumber(status_);
      return result == null ? ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Status.UNRECOGNIZED : result;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_ = 0;
    /**
     * <code>.ch.heigvd.iict.dma.labo1.protobuf.Measure.Type type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.ch.heigvd.iict.dma.labo1.protobuf.Measure.Type type = 3;</code>
     * @return The type.
     */
    @java.lang.Override public ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Type getType() {
      ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Type result = ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Type.forNumber(type_);
      return result == null ? ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Type.UNRECOGNIZED : result;
    }

    public static final int VALUE_FIELD_NUMBER = 4;
    private double value_ = 0D;
    /**
     * <code>double value = 4;</code>
     * @return The value.
     */
    @java.lang.Override
    public double getValue() {
      return value_;
    }

    public static final int DATE_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp date_;
    /**
     * <code>.google.protobuf.Timestamp date = 5;</code>
     * @return Whether the date field is set.
     */
    @java.lang.Override
    public boolean hasDate() {
      return date_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 5;</code>
     * @return The date.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getDate() {
      return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getDateOrBuilder() {
      return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (status_ != ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Status.NEW.getNumber()) {
        output.writeEnum(2, status_);
      }
      if (type_ != ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Type.TEMPERATURE.getNumber()) {
        output.writeEnum(3, type_);
      }
      if (java.lang.Double.doubleToRawLongBits(value_) != 0) {
        output.writeDouble(4, value_);
      }
      if (date_ != null) {
        output.writeMessage(5, getDate());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (status_ != ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Status.NEW.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_);
      }
      if (type_ != ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Type.TEMPERATURE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      if (java.lang.Double.doubleToRawLongBits(value_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, value_);
      }
      if (date_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getDate());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure)) {
        return super.equals(obj);
      }
      ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure other = (ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure) obj;

      if (getId()
          != other.getId()) return false;
      if (status_ != other.status_) return false;
      if (type_ != other.type_) return false;
      if (java.lang.Double.doubleToLongBits(getValue())
          != java.lang.Double.doubleToLongBits(
              other.getValue())) return false;
      if (hasDate() != other.hasDate()) return false;
      if (hasDate()) {
        if (!getDate()
            .equals(other.getDate())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getValue()));
      if (hasDate()) {
        hash = (37 * hash) + DATE_FIELD_NUMBER;
        hash = (53 * hash) + getDate().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ch.heigvd.iict.dma.labo1.protobuf.Measure}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ch.heigvd.iict.dma.labo1.protobuf.Measure)
        ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.MeasureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.internal_static_ch_heigvd_iict_dma_labo1_protobuf_Measure_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.internal_static_ch_heigvd_iict_dma_labo1_protobuf_Measure_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.class, ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Builder.class);
      }

      // Construct using ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        status_ = 0;
        type_ = 0;
        value_ = 0D;
        date_ = null;
        if (dateBuilder_ != null) {
          dateBuilder_.dispose();
          dateBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.internal_static_ch_heigvd_iict_dma_labo1_protobuf_Measure_descriptor;
      }

      @java.lang.Override
      public ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure getDefaultInstanceForType() {
        return ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.getDefaultInstance();
      }

      @java.lang.Override
      public ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure build() {
        ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure buildPartial() {
        ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure result = new ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.status_ = status_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.value_ = value_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.date_ = dateBuilder_ == null
              ? date_
              : dateBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure) {
          return mergeFrom((ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure other) {
        if (other == ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getValue() != 0D) {
          setValue(other.getValue());
        }
        if (other.hasDate()) {
          mergeDate(other.getDate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                status_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 33: {
                value_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              case 42: {
                input.readMessage(
                    getDateFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.ch.heigvd.iict.dma.labo1.protobuf.Measure.Status status = 2;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.ch.heigvd.iict.dma.labo1.protobuf.Measure.Status status = 2;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.ch.heigvd.iict.dma.labo1.protobuf.Measure.Status status = 2;</code>
       * @return The status.
       */
      @java.lang.Override
      public ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Status getStatus() {
        ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Status result = ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Status.forNumber(status_);
        return result == null ? ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.ch.heigvd.iict.dma.labo1.protobuf.Measure.Status status = 2;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ch.heigvd.iict.dma.labo1.protobuf.Measure.Status status = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.ch.heigvd.iict.dma.labo1.protobuf.Measure.Type type = 3;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.ch.heigvd.iict.dma.labo1.protobuf.Measure.Type type = 3;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.ch.heigvd.iict.dma.labo1.protobuf.Measure.Type type = 3;</code>
       * @return The type.
       */
      @java.lang.Override
      public ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Type getType() {
        ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Type result = ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Type.forNumber(type_);
        return result == null ? ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.ch.heigvd.iict.dma.labo1.protobuf.Measure.Type type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ch.heigvd.iict.dma.labo1.protobuf.Measure.Type type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        onChanged();
        return this;
      }

      private double value_ ;
      /**
       * <code>double value = 4;</code>
       * @return The value.
       */
      @java.lang.Override
      public double getValue() {
        return value_;
      }
      /**
       * <code>double value = 4;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(double value) {

        value_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double value = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = 0D;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp date_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateBuilder_;
      /**
       * <code>.google.protobuf.Timestamp date = 5;</code>
       * @return Whether the date field is set.
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp date = 5;</code>
       * @return The date.
       */
      public com.google.protobuf.Timestamp getDate() {
        if (dateBuilder_ == null) {
          return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
        } else {
          return dateBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp date = 5;</code>
       */
      public Builder setDate(com.google.protobuf.Timestamp value) {
        if (dateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          date_ = value;
        } else {
          dateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp date = 5;</code>
       */
      public Builder setDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (dateBuilder_ == null) {
          date_ = builderForValue.build();
        } else {
          dateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp date = 5;</code>
       */
      public Builder mergeDate(com.google.protobuf.Timestamp value) {
        if (dateBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            date_ != null &&
            date_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getDateBuilder().mergeFrom(value);
          } else {
            date_ = value;
          }
        } else {
          dateBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp date = 5;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000010);
        date_ = null;
        if (dateBuilder_ != null) {
          dateBuilder_.dispose();
          dateBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp date = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getDateBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getDateFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp date = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDateOrBuilder() {
        if (dateBuilder_ != null) {
          return dateBuilder_.getMessageOrBuilder();
        } else {
          return date_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : date_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp date = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getDateFieldBuilder() {
        if (dateBuilder_ == null) {
          dateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDate(),
                  getParentForChildren(),
                  isClean());
          date_ = null;
        }
        return dateBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ch.heigvd.iict.dma.labo1.protobuf.Measure)
    }

    // @@protoc_insertion_point(class_scope:ch.heigvd.iict.dma.labo1.protobuf.Measure)
    private static final ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure();
    }

    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Measure>
        PARSER = new com.google.protobuf.AbstractParser<Measure>() {
      @java.lang.Override
      public Measure parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Measure> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Measure> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MeasuresOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ch.heigvd.iict.dma.labo1.protobuf.Measures)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
     */
    java.util.List<ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure> 
        getMeasuresList();
    /**
     * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
     */
    ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure getMeasures(int index);
    /**
     * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
     */
    int getMeasuresCount();
    /**
     * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
     */
    java.util.List<? extends ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.MeasureOrBuilder> 
        getMeasuresOrBuilderList();
    /**
     * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
     */
    ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.MeasureOrBuilder getMeasuresOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ch.heigvd.iict.dma.labo1.protobuf.Measures}
   */
  public static final class Measures extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ch.heigvd.iict.dma.labo1.protobuf.Measures)
      MeasuresOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Measures.newBuilder() to construct.
    private Measures(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Measures() {
      measures_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Measures();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.internal_static_ch_heigvd_iict_dma_labo1_protobuf_Measures_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.internal_static_ch_heigvd_iict_dma_labo1_protobuf_Measures_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures.class, ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures.Builder.class);
    }

    public static final int MEASURES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure> measures_;
    /**
     * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
     */
    @java.lang.Override
    public java.util.List<ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure> getMeasuresList() {
      return measures_;
    }
    /**
     * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.MeasureOrBuilder> 
        getMeasuresOrBuilderList() {
      return measures_;
    }
    /**
     * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
     */
    @java.lang.Override
    public int getMeasuresCount() {
      return measures_.size();
    }
    /**
     * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
     */
    @java.lang.Override
    public ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure getMeasures(int index) {
      return measures_.get(index);
    }
    /**
     * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
     */
    @java.lang.Override
    public ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.MeasureOrBuilder getMeasuresOrBuilder(
        int index) {
      return measures_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < measures_.size(); i++) {
        output.writeMessage(1, measures_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < measures_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, measures_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures)) {
        return super.equals(obj);
      }
      ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures other = (ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures) obj;

      if (!getMeasuresList()
          .equals(other.getMeasuresList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMeasuresCount() > 0) {
        hash = (37 * hash) + MEASURES_FIELD_NUMBER;
        hash = (53 * hash) + getMeasuresList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ch.heigvd.iict.dma.labo1.protobuf.Measures}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ch.heigvd.iict.dma.labo1.protobuf.Measures)
        ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.MeasuresOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.internal_static_ch_heigvd_iict_dma_labo1_protobuf_Measures_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.internal_static_ch_heigvd_iict_dma_labo1_protobuf_Measures_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures.class, ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures.Builder.class);
      }

      // Construct using ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (measuresBuilder_ == null) {
          measures_ = java.util.Collections.emptyList();
        } else {
          measures_ = null;
          measuresBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.internal_static_ch_heigvd_iict_dma_labo1_protobuf_Measures_descriptor;
      }

      @java.lang.Override
      public ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures getDefaultInstanceForType() {
        return ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures.getDefaultInstance();
      }

      @java.lang.Override
      public ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures build() {
        ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures buildPartial() {
        ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures result = new ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures result) {
        if (measuresBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            measures_ = java.util.Collections.unmodifiableList(measures_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.measures_ = measures_;
        } else {
          result.measures_ = measuresBuilder_.build();
        }
      }

      private void buildPartial0(ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures) {
          return mergeFrom((ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures other) {
        if (other == ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures.getDefaultInstance()) return this;
        if (measuresBuilder_ == null) {
          if (!other.measures_.isEmpty()) {
            if (measures_.isEmpty()) {
              measures_ = other.measures_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMeasuresIsMutable();
              measures_.addAll(other.measures_);
            }
            onChanged();
          }
        } else {
          if (!other.measures_.isEmpty()) {
            if (measuresBuilder_.isEmpty()) {
              measuresBuilder_.dispose();
              measuresBuilder_ = null;
              measures_ = other.measures_;
              bitField0_ = (bitField0_ & ~0x00000001);
              measuresBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMeasuresFieldBuilder() : null;
            } else {
              measuresBuilder_.addAllMessages(other.measures_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure m =
                    input.readMessage(
                        ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.parser(),
                        extensionRegistry);
                if (measuresBuilder_ == null) {
                  ensureMeasuresIsMutable();
                  measures_.add(m);
                } else {
                  measuresBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure> measures_ =
        java.util.Collections.emptyList();
      private void ensureMeasuresIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          measures_ = new java.util.ArrayList<ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure>(measures_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure, ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Builder, ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.MeasureOrBuilder> measuresBuilder_;

      /**
       * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
       */
      public java.util.List<ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure> getMeasuresList() {
        if (measuresBuilder_ == null) {
          return java.util.Collections.unmodifiableList(measures_);
        } else {
          return measuresBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
       */
      public int getMeasuresCount() {
        if (measuresBuilder_ == null) {
          return measures_.size();
        } else {
          return measuresBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
       */
      public ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure getMeasures(int index) {
        if (measuresBuilder_ == null) {
          return measures_.get(index);
        } else {
          return measuresBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
       */
      public Builder setMeasures(
          int index, ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure value) {
        if (measuresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMeasuresIsMutable();
          measures_.set(index, value);
          onChanged();
        } else {
          measuresBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
       */
      public Builder setMeasures(
          int index, ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Builder builderForValue) {
        if (measuresBuilder_ == null) {
          ensureMeasuresIsMutable();
          measures_.set(index, builderForValue.build());
          onChanged();
        } else {
          measuresBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
       */
      public Builder addMeasures(ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure value) {
        if (measuresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMeasuresIsMutable();
          measures_.add(value);
          onChanged();
        } else {
          measuresBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
       */
      public Builder addMeasures(
          int index, ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure value) {
        if (measuresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMeasuresIsMutable();
          measures_.add(index, value);
          onChanged();
        } else {
          measuresBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
       */
      public Builder addMeasures(
          ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Builder builderForValue) {
        if (measuresBuilder_ == null) {
          ensureMeasuresIsMutable();
          measures_.add(builderForValue.build());
          onChanged();
        } else {
          measuresBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
       */
      public Builder addMeasures(
          int index, ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Builder builderForValue) {
        if (measuresBuilder_ == null) {
          ensureMeasuresIsMutable();
          measures_.add(index, builderForValue.build());
          onChanged();
        } else {
          measuresBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
       */
      public Builder addAllMeasures(
          java.lang.Iterable<? extends ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure> values) {
        if (measuresBuilder_ == null) {
          ensureMeasuresIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, measures_);
          onChanged();
        } else {
          measuresBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
       */
      public Builder clearMeasures() {
        if (measuresBuilder_ == null) {
          measures_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          measuresBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
       */
      public Builder removeMeasures(int index) {
        if (measuresBuilder_ == null) {
          ensureMeasuresIsMutable();
          measures_.remove(index);
          onChanged();
        } else {
          measuresBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
       */
      public ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Builder getMeasuresBuilder(
          int index) {
        return getMeasuresFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
       */
      public ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.MeasureOrBuilder getMeasuresOrBuilder(
          int index) {
        if (measuresBuilder_ == null) {
          return measures_.get(index);  } else {
          return measuresBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
       */
      public java.util.List<? extends ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.MeasureOrBuilder> 
           getMeasuresOrBuilderList() {
        if (measuresBuilder_ != null) {
          return measuresBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(measures_);
        }
      }
      /**
       * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
       */
      public ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Builder addMeasuresBuilder() {
        return getMeasuresFieldBuilder().addBuilder(
            ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.getDefaultInstance());
      }
      /**
       * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
       */
      public ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Builder addMeasuresBuilder(
          int index) {
        return getMeasuresFieldBuilder().addBuilder(
            index, ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.getDefaultInstance());
      }
      /**
       * <code>repeated .ch.heigvd.iict.dma.labo1.protobuf.Measure measures = 1;</code>
       */
      public java.util.List<ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Builder> 
           getMeasuresBuilderList() {
        return getMeasuresFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure, ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Builder, ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.MeasureOrBuilder> 
          getMeasuresFieldBuilder() {
        if (measuresBuilder_ == null) {
          measuresBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure, ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measure.Builder, ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.MeasureOrBuilder>(
                  measures_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          measures_ = null;
        }
        return measuresBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ch.heigvd.iict.dma.labo1.protobuf.Measures)
    }

    // @@protoc_insertion_point(class_scope:ch.heigvd.iict.dma.labo1.protobuf.Measures)
    private static final ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures();
    }

    public static ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Measures>
        PARSER = new com.google.protobuf.AbstractParser<Measures>() {
      @java.lang.Override
      public Measures parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Measures> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Measures> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ch.heigvd.iict.dma.labo1.protobuf.MeasuresOuterClass.Measures getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch_heigvd_iict_dma_labo1_protobuf_Measure_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch_heigvd_iict_dma_labo1_protobuf_Measure_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch_heigvd_iict_dma_labo1_protobuf_Measures_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ch_heigvd_iict_dma_labo1_protobuf_Measures_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016measures.proto\022!ch.heigvd.iict.dma.lab" +
      "o1.protobuf\032\037google/protobuf/timestamp.p" +
      "roto\"\276\002\n\007Measure\022\n\n\002id\030\001 \001(\005\022A\n\006status\030\002" +
      " \001(\01621.ch.heigvd.iict.dma.labo1.protobuf" +
      ".Measure.Status\022=\n\004type\030\003 \001(\0162/.ch.heigv" +
      "d.iict.dma.labo1.protobuf.Measure.Type\022\r" +
      "\n\005value\030\004 \001(\001\022(\n\004date\030\005 \001(\0132\032.google.pro" +
      "tobuf.Timestamp\"$\n\006Status\022\007\n\003NEW\020\000\022\006\n\002OK" +
      "\020\001\022\t\n\005ERROR\020\002\"F\n\004Type\022\017\n\013TEMPERATURE\020\000\022\021" +
      "\n\rPRECIPITATION\020\001\022\014\n\010HUMIDITY\020\002\022\014\n\010PRESS" +
      "URE\020\003\"H\n\010Measures\022<\n\010measures\030\001 \003(\0132*.ch" +
      ".heigvd.iict.dma.labo1.protobuf.Measureb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_ch_heigvd_iict_dma_labo1_protobuf_Measure_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ch_heigvd_iict_dma_labo1_protobuf_Measure_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch_heigvd_iict_dma_labo1_protobuf_Measure_descriptor,
        new java.lang.String[] { "Id", "Status", "Type", "Value", "Date", });
    internal_static_ch_heigvd_iict_dma_labo1_protobuf_Measures_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ch_heigvd_iict_dma_labo1_protobuf_Measures_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ch_heigvd_iict_dma_labo1_protobuf_Measures_descriptor,
        new java.lang.String[] { "Measures", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
